site_name: KRW's Page
site_url: https://krw.run.place

# Repository
repo_name: KingRootwang/KingRootwang.github.io
repo_url: https://github.com/KingRootwang/KingRootwang.github.io
theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/sun-angle
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon:   material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

plugins:
  - search
  - blog

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Note 4 Links: links.md
  - Welcome: welcome.md
  - Blog:
     - blog/index.md
