site_name: KRW's Page
site_url: https://krw.run.place/index

# Repository
repo_name: KingRootwang/kingrootwang.github.io
repo_url: https://github.com/KingRootwang/kingrootwang.github.io/
theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/sun-angle
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon:   material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
nav:
  - Home: docs/index.md
  - Welcome: docs/welcome.md